version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    ports:
      - 27017:27017
    networks:
      - portfolio-network
    volumes:
      - ./data/db:/data/db
    # command:
    #   mongoimport --host mongodb --db portfolio --type json --file /mongo/init_data/failure_modes.json --jsonArray
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: caixia

  nginx:
    image: nginx
    container_name: nginx-container
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3001:80"
    networks:
      - portfolio-network

  client:
    image: portfolio-client
    container_name: client-container
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - portfolio-network
    build:
      dockerfile: Dockerfile
      context: ./frontend
    command: serve -s build -l 3000

  api:
    image: portfolio-api
    container_name: api-container
    build:
      dockerfile: Dockerfile
      context: "./backend"
    networks:
      - portfolio-network
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    environment:
      ENV: prod
      PORT: 5000
      NODE_ENV: production
      MONGO_HOST_URL: mongodb://root:caixia@mongo:27017/portfolio?authSource=admin
    restart: unless-stopped
networks:
  portfolio-network:
    driver: bridge
  # mongo_seed:
  #   image: mongo
  #   links:
  #     - mongo
  #   volumes:
  #     - ./data/backup:data/backup
  #   command:
  #     /data/import.sh

  # mongo-cron-backup:
  #   build: ./cron
  #   environment:
  #     - MONGODB_DATABASE=portfolio
  #     - MONGODB_HOST=mongo
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=caixia
  #     - MONGODB_PORT=27017
  #     - CRON_EXPRESSION=1 12   *
  #     - LOCAL_PATH=./data/backup
  #     - DESTINATION_PATH=/var/opt/mongobackup
  #   image: thelebster/mongo-cron-backup
  #   hostname: mongo-cron-backup
  #   container_name: mongo-cron-backup
  #   restart: always
  #   # Uncomment if runs on the same host and you will be able to access mongo on 127.0.0.1:27017
  #   network_mode: "host"
  #   volumes:
  #     - ./data/backup:/var/opt/mongobackup:rw
  #   depends_on:
  #     - mongo
